name: Update Dependency Graph

on:
  push:
    branches:
      - main

jobs:
  submit:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
        with:
          fetch-depth: 0

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@db19848a5fa7950289d3668fb053140cf3028d43 # v3

      - name: Download Java JDK
        uses: typelevel/download-java@817e8c0d48dc2e88e155a8e4f69ba493bef621be # v2
        id: download-java
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Java JDK
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
        with:
          distribution: jdkfile
          java-version: 11
          jdkFile: ${{ steps.download-java.outputs.jdkFile }}

      - name: Generate Dependency Graph Snapshot
        uses: gradle/actions/dependency-submission@db19848a5fa7950289d3668fb053140cf3028d43 # v3
        env:
          DEPENDENCY_GRAPH_INCLUDE_CONFIGURATIONS: "compileClasspath|runtimeClasspath"
